repos:
- repo: local
  hooks:
    - id: Name check
      name: Check sensitive info
      verbose: true
      language: script
      entry: pre_commit_hooks/rtx.sh
    - id: IP check
      name: Check sensitive info
      verbose: true
      language: script
      entry: pre_commit_hooks/ip.sh
    - id: isort
      name: isort
      language: python
      types: [python]
      pass_filenames: false
      entry: isort --settings-path=src/api/pyproject.toml .
    - id: black
      name: black
      language: python
      types: [python]
      pass_filenames: false
      entry: black --config=src/api/pyproject.toml .
    - id: flake8
      name: flak8
      language: python
      types: [python]
      pass_filenames: false
      entry: pflake8 --config=src/api/pyproject.toml
    - id: mypy
      name: mypy
      language: python
      types: [python]
      pass_filenames: false
      entry: mypy src/ --config-file=src/api/pyproject.toml